services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test12345
    volumes:
      - ./neo4j_data:/data